
import React, { useRef, useState } from 'react';
import { FinancialAnalysis, Language } from '../types';
import { 
  TrendingUp, 
  TrendingDown, 
  Minus, 
  Target, 
  Lightbulb, 
  Download, 
  PieChart, 
  Activity,
  FileText,
  Info,
  Building2,
  Calendar,
  BarChart3,
  ShieldAlert,
  Zap,
  CheckCircle2,
  ArrowUpRight,
  Presentation
} from 'lucide-react';
import { RevenueProfitChart, CostStructureChart, HealthRadarChart, MarginTrendChart } from './Charts';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import PptxGenJS from 'pptxgenjs';
import clsx from 'clsx';

interface ReportProps {
  data: FinancialAnalysis;
  onReset: () => void;
  language: Language;
}

const translations = {
  it: {
    confidential: "Confidenziale",
    period: "Periodo Analizzato",
    execSummary: "Executive Summary",
    healthIndex: "Indice di Salute Finanziaria",
    kpi: "Indicatori Chiave di Performance",
    swot: "Analisi SWOT",
    strengths: "Punti di Forza",
    weaknesses: "Punti di Debolezza",
    opportunities: "Opportunità",
    threats: "Minacce",
    profitability: "Analisi Redditività",
    liquidity: "Analisi Liquidità",
    strategic: "Insight Strategici",
    recommendations: "Raccomandazioni",
    generatedBy: "Report generato da FinSight AI",
    newAnalysis: "Nuova Analisi",
    exportPPT: "Esporta PPT",
    exportPDF: "Esporta PDF",
    genPPT: "Generazione PPT...",
    genPDF: "Generazione PDF...",
    revProfitTrend: "Trend Fatturato vs Utile",
    ebitdaMargin: "Analisi Margine EBITDA",
    costStructure: "Struttura Costi e Flussi",
    liquidityAnalysis: "Analisi della Liquidità"
  },
  en: {
    confidential: "Confidential",
    period: "Analyzed Period",
    execSummary: "Executive Summary",
    healthIndex: "Financial Health Index",
    kpi: "Key Performance Indicators",
    swot: "SWOT Analysis",
    strengths: "Strengths",
    weaknesses: "Weaknesses",
    opportunities: "Opportunities",
    threats: "Threats",
    profitability: "Profitability Analysis",
    liquidity: "Liquidity Analysis",
    strategic: "Strategic Insights",
    recommendations: "Recommendations",
    generatedBy: "Report generated by FinSight AI",
    newAnalysis: "New Analysis",
    exportPPT: "Export PPT",
    exportPDF: "Export PDF",
    genPPT: "Generating PPT...",
    genPDF: "Generating PDF...",
    revProfitTrend: "Revenue vs Profit Trend",
    ebitdaMargin: "EBITDA Margin Analysis",
    costStructure: "Cost Structure & Cash Flow",
    liquidityAnalysis: "Liquidity Analysis"
  },
  es: {
    confidential: "Confidencial",
    period: "Período Analizado",
    execSummary: "Resumen Ejecutivo",
    healthIndex: "Índice de Salud Financiera",
    kpi: "Indicadores Clave de Rendimiento",
    swot: "Análisis SWOT",
    strengths: "Fortalezas",
    weaknesses: "Debilidades",
    opportunities: "Oportunidades",
    threats: "Amenazas",
    profitability: "Análisis de Rentabilidad",
    liquidity: "Análisis de Liquidez",
    strategic: "Insights Estratégicos",
    recommendations: "Recomendaciones",
    generatedBy: "Informe generado por FinSight AI",
    newAnalysis: "Nuevo Análisis",
    exportPPT: "Exportar PPT",
    exportPDF: "Exportar PDF",
    genPPT: "Generando PPT...",
    genPDF: "Generando PDF...",
    revProfitTrend: "Tendencia Ingresos vs Beneficios",
    ebitdaMargin: "Análisis Margen EBITDA",
    costStructure: "Estructura de Costos y Flujo de Caja",
    liquidityAnalysis: "Análisis de Liquidez"
  },
  fr: {
    confidential: "Confidentiel",
    period: "Période Analysée",
    execSummary: "Résumé Exécutif",
    healthIndex: "Indice de Santé Financière",
    kpi: "Indicateurs Clés de Performance",
    swot: "Analyse SWOT",
    strengths: "Forces",
    weaknesses: "Faiblesses",
    opportunities: "Opportunités",
    threats: "Menaces",
    profitability: "Analyse de Rentabilité",
    liquidity: "Analyse de Liquidité",
    strategic: "Insights Stratégiques",
    recommendations: "Recommandations",
    generatedBy: "Rapport généré par FinSight AI",
    newAnalysis: "Nouvelle Analyse",
    exportPPT: "Exporter PPT",
    exportPDF: "Exporter PDF",
    genPPT: "Génération PPT...",
    genPDF: "Génération PDF...",
    revProfitTrend: "Tendance Revenus vs Bénéfices",
    ebitdaMargin: "Analyse Marge EBITDA",
    costStructure: "Structure des Coûts et Flux de Trésorerie",
    liquidityAnalysis: "Analyse de Liquidité"
  },
  de: {
    confidential: "Vertraulich",
    period: "Analysierter Zeitraum",
    execSummary: "Executive Summary",
    healthIndex: "Finanzgesundheitsindex",
    kpi: "Leistungskennzahlen (KPIs)",
    swot: "SWOT-Analyse",
    strengths: "Stärken",
    weaknesses: "Schwächen",
    opportunities: "Chancen",
    threats: "Bedrohungen",
    profitability: "Rentabilitätsanalyse",
    liquidity: "Liquiditätsanalyse",
    strategic: "Strategische Einblicke",
    recommendations: "Empfehlungen",
    generatedBy: "Bericht erstellt von FinSight AI",
    newAnalysis: "Neue Analyse",
    exportPPT: "PPT Exportieren",
    exportPDF: "PDF Exportieren",
    genPPT: "Erstelle PPT...",
    genPDF: "Erstelle PDF...",
    revProfitTrend: "Umsatz vs. Gewinn Trend",
    ebitdaMargin: "EBITDA Marge Analyse",
    costStructure: "Kostenstruktur & Cashflow",
    liquidityAnalysis: "Liquiditätsanalyse"
  }
};

export const Report: React.FC<ReportProps> = ({ data, onReset, language }) => {
  const reportRef = useRef<HTMLDivElement>(null);
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [isExportingPpt, setIsExportingPpt] = useState(false);
  
  const t = translations[language] || translations.it;

  // Helper to capture a DOM element as an image
  const captureSection = async (element: HTMLElement, scale = 2) => {
    return await html2canvas(element, {
      scale: scale,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      ignoreElements: (element) => element.classList.contains('no-print')
    });
  };

  const handleExportPDF = async () => {
    if (!reportRef.current) return;
    setIsExportingPdf(true);
    
    try {
      const container = reportRef.current;
      // Get all sections marked for export
      const sections = container.querySelectorAll<HTMLElement>('.report-section');
      
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();

      for (let i = 0; i < sections.length; i++) {
        const section = sections[i];
        
        // Add a new page for subsequent sections
        if (i > 0) pdf.addPage();

        const canvas = await captureSection(section);
        const imgData = canvas.toDataURL('image/png');
        
        // Calculate dimensions to fit width, maintaining aspect ratio
        const imgProps = pdf.getImageProperties(imgData);
        const ratio = imgProps.width / imgProps.height;
        const width = pdfWidth;
        const height = width / ratio;

        // If height > page height, we might need to scale down further or accept it fits logic
        // For this specific design, sections are designed to fit on a page usually.
        pdf.addImage(imgData, 'PNG', 0, 0, width, height);
      }

      pdf.save(`FinSight_${data.companyName.replace(/\s+/g, '_')}.pdf`);
    } catch (err) {
      console.error(err);
      alert('Errore durante l\'esportazione del PDF');
    } finally {
      setIsExportingPdf(false);
    }
  };

  const handleExportPPT = async () => {
    if (!reportRef.current) return;
    setIsExportingPpt(true);

    try {
        const pres = new PptxGenJS();
        pres.layout = 'LAYOUT_16x9';
        pres.title = `Financial Analysis - ${data.companyName}`;
        pres.author = 'FinSight AI';

        const container = reportRef.current;
        const sections = container.querySelectorAll<HTMLElement>('.report-section');

        for (let i = 0; i < sections.length; i++) {
            const section = sections[i];
            
            // Capture high quality image of the section
            const canvas = await captureSection(section, 2); 
            const imgData = canvas.toDataURL('image/png');

            const slide = pres.addSlide();
            
            // Add the image to the slide, fitting it nicely
            slide.addImage({
                data: imgData,
                x: 0,
                y: 0,
                w: '100%',
                h: '100%',
                sizing: { type: 'contain', align: 'center', valign: 'middle' } // Ensures no cutting
            });
        }

        await pres.writeFile({ fileName: `FinSight_${data.companyName.replace(/\s+/g, '_')}.pptx` });

    } catch (err) {
        console.error(err);
        alert('Errore durante l\'esportazione del PowerPoint');
    } finally {
        setIsExportingPpt(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Tools Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4 no-print">
        <button 
            onClick={onReset}
            className="text-slate-500 hover:text-slate-800 font-medium flex items-center gap-2 transition-colors"
        >
            ← {t.newAnalysis}
        </button>
        <div className="flex gap-3">
             <button 
                onClick={handleExportPPT}
                disabled={isExportingPpt || isExportingPdf}
                className="flex items-center gap-2 px-5 py-2.5 bg-orange-600 text-white rounded-full hover:bg-orange-700 font-medium transition-all shadow-lg hover:shadow-xl disabled:opacity-50"
            >
                {isExportingPpt ? t.genPPT : <><Presentation size={18} /> {t.exportPPT}</>}
            </button>
            <button 
                onClick={handleExportPDF}
                disabled={isExportingPpt || isExportingPdf}
                className="flex items-center gap-2 px-5 py-2.5 bg-slate-900 text-white rounded-full hover:bg-slate-800 font-medium transition-all shadow-lg hover:shadow-xl disabled:opacity-50"
            >
                {isExportingPdf ? t.genPDF : <><Download size={18} /> {t.exportPDF}</>}
            </button>
        </div>
       
      </div>

      {/* Report Container - Logic: Each 'report-section' becomes a Page/Slide */}
      <div ref={reportRef} className="space-y-8">
        
        {/* === SECTION 1: COVER === */}
        <div className="report-section bg-white shadow-xl rounded-none sm:rounded-2xl overflow-hidden border border-slate-200">
            <div className="relative bg-slate-900 text-white p-12 overflow-hidden h-full min-h-[500px] flex flex-col justify-center">
                <div className="absolute top-0 right-0 p-12 opacity-10">
                    <BarChart3 size={400} />
                </div>
                <div className="relative z-10">
                    <div className="flex items-center gap-3 mb-6">
                        <span className="bg-blue-600 px-3 py-1 rounded text-xs font-bold uppercase tracking-widest">{t.confidential}</span>
                        <span className="text-slate-400 text-sm flex items-center gap-1"><Calendar size={14}/> {new Date().toLocaleDateString(language === 'en' ? 'en-US' : 'it-IT')}</span>
                    </div>
                    <h1 className="text-6xl font-extrabold tracking-tight mb-6 leading-tight">{data.companyName}</h1>
                    <p className="text-2xl text-slate-300 font-light flex items-center gap-3">
                        <Building2 size={24} className="text-blue-400"/>
                        Strategic Financial Assessment
                    </p>
                    <div className="mt-12 flex items-center gap-4">
                        <div className="bg-white/10 backdrop-blur-md px-6 py-4 rounded-xl border border-white/10">
                            <div className="text-xs text-slate-400 uppercase tracking-wider mb-1">{t.period}</div>
                            <div className="font-semibold text-lg">{data.reportDate || "N/A"}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {/* === SECTION 2: EXEC SUMMARY & SCORE === */}
        <div className="report-section bg-white shadow-xl rounded-none sm:rounded-2xl overflow-hidden border border-slate-200">
            <div className="grid grid-cols-1 lg:grid-cols-3 h-full">
                <div className="lg:col-span-2 p-12 flex flex-col justify-center">
                    <h2 className="text-3xl font-bold text-slate-800 mb-8 flex items-center gap-3">
                        <Activity className="text-blue-600" size={32} /> {t.execSummary}
                    </h2>
                    <div className="prose prose-slate max-w-none text-slate-600 text-justify leading-loose text-lg">
                        <p className="whitespace-pre-wrap">{data.executiveSummary}</p>
                    </div>
                    {data.methodology && (
                        <div className="mt-8 flex items-start gap-2 text-sm text-slate-400 bg-slate-50 p-4 rounded-lg border border-slate-100">
                            <Info size={16} className="mt-0.5 flex-shrink-0" />
                            <span>{data.methodology}</span>
                        </div>
                    )}
                </div>
                
                <div className="bg-slate-50 p-10 border-l border-slate-200 flex flex-col items-center justify-center">
                    <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-8">{t.healthIndex}</h3>
                    <div className="relative flex items-center justify-center mb-8">
                        <svg className="w-48 h-48 transform -rotate-90">
                            <circle cx="96" cy="96" r="80" stroke="#e2e8f0" strokeWidth="16" fill="transparent" />
                            <circle cx="96" cy="96" r="80" stroke="currentColor" strokeWidth="16" fill="transparent" 
                                strokeDasharray={502} 
                                strokeDashoffset={502 - (502 * data.financialHealthScore) / 100} 
                                strokeLinecap="round"
                                className={clsx(
                                    "transition-all duration-1000 ease-out",
                                    data.financialHealthScore >= 80 ? "text-emerald-500" :
                                    data.financialHealthScore >= 60 ? "text-blue-500" :
                                    data.financialHealthScore >= 40 ? "text-yellow-500" : "text-red-500"
                                )} 
                            />
                        </svg>
                        <div className="absolute flex flex-col items-center">
                            <span className="text-6xl font-bold text-slate-800">{data.financialHealthScore}</span>
                            <span className="text-lg text-slate-400">/ 100</span>
                        </div>
                    </div>
                    
                    <div className="w-full mt-4 h-[300px]">
                        <HealthRadarChart data={data.healthRadar} />
                    </div>
                </div>
            </div>
        </div>

        {/* === SECTION 3: KPI DASHBOARD === */}
        <div className="report-section bg-white shadow-xl rounded-none sm:rounded-2xl overflow-hidden border border-slate-200 p-12">
            <h3 className="text-2xl font-bold text-slate-800 mb-10 flex items-center gap-3">
                <Target className="text-rose-500" size={28} /> {t.kpi}
            </h3>
            <div className="grid grid-cols-2 gap-8">
                {data.kpis.map((kpi, idx) => (
                    <div key={idx} className="p-6 rounded-2xl border border-slate-200 bg-white hover:border-blue-300 transition-colors shadow-sm">
                        <div className="flex justify-between items-start mb-3">
                            <span className="text-sm font-bold text-slate-400 uppercase tracking-wider">{kpi.label}</span>
                            {kpi.trend === 'up' && <TrendingUp className="text-emerald-500" size={24} />}
                            {kpi.trend === 'down' && <TrendingDown className="text-rose-500" size={24} />}
                            {kpi.trend === 'neutral' && <Minus className="text-slate-400" size={24} />}
                        </div>
                        <div className="flex items-baseline gap-2 mb-4">
                            <span className="text-4xl font-bold text-slate-800">{kpi.value}</span>
                            <span className="text-lg font-medium text-slate-400">{kpi.unit}</span>
                        </div>
                        <div className="text-sm text-slate-500 leading-snug border-t border-slate-100 pt-4">
                            {kpi.insight}
                        </div>
                    </div>
                ))}
            </div>
        </div>

        {/* === SECTION 4: SWOT ANALYSIS === */}
        <div className="report-section bg-slate-50 shadow-xl rounded-none sm:rounded-2xl overflow-hidden border border-slate-200 p-12">
             <h3 className="text-2xl font-bold text-slate-800 mb-10 flex items-center gap-3">
                <CheckCircle2 className="text-emerald-600" size={28} /> {t.swot}
            </h3>
            <div className="grid grid-cols-2 gap-8 h-full">
                <div className="bg-white p-8 rounded-xl border-l-8 border-emerald-500 shadow-sm">
                    <div className="flex items-center gap-3 mb-6 text-emerald-700 font-bold text-lg">
                        <Zap size={24} /> {t.strengths}
                    </div>
                    <ul className="space-y-4">
                        {data.swotAnalysis.strengths.map((item, i) => (
                            <li key={i} className="flex items-start gap-3 text-base text-slate-700">
                                <span className="mt-2 w-2 h-2 rounded-full bg-emerald-400 flex-shrink-0" />
                                {item}
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="bg-white p-8 rounded-xl border-l-8 border-rose-500 shadow-sm">
                    <div className="flex items-center gap-3 mb-6 text-rose-700 font-bold text-lg">
                        <ShieldAlert size={24} /> {t.weaknesses}
                    </div>
                    <ul className="space-y-4">
                        {data.swotAnalysis.weaknesses.map((item, i) => (
                            <li key={i} className="flex items-start gap-3 text-base text-slate-700">
                                <span className="mt-2 w-2 h-2 rounded-full bg-rose-400 flex-shrink-0" />
                                {item}
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="bg-white p-8 rounded-xl border-l-8 border-blue-500 shadow-sm">
                    <div className="flex items-center gap-3 mb-6 text-blue-700 font-bold text-lg">
                        <ArrowUpRight size={24} /> {t.opportunities}
                    </div>
                    <ul className="space-y-4">
                        {data.swotAnalysis.opportunities.map((item, i) => (
                            <li key={i} className="flex items-start gap-3 text-base text-slate-700">
                                <span className="mt-2 w-2 h-2 rounded-full bg-blue-400 flex-shrink-0" />
                                {item}
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="bg-white p-8 rounded-xl border-l-8 border-amber-500 shadow-sm">
                    <div className="flex items-center gap-3 mb-6 text-amber-700 font-bold text-lg">
                        <Activity size={24} /> {t.threats}
                    </div>
                    <ul className="space-y-4">
                        {data.swotAnalysis.threats.map((item, i) => (
                            <li key={i} className="flex items-start gap-3 text-base text-slate-700">
                                <span className="mt-2 w-2 h-2 rounded-full bg-amber-400 flex-shrink-0" />
                                {item}
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>

        {/* === SECTION 5: PROFITABILITY DEEP DIVE === */}
        <div className="report-section bg-white shadow-xl rounded-none sm:rounded-2xl overflow-hidden border border-slate-200 p-12">
            <div className="flex items-center gap-4 mb-8">
                <div className="p-3 bg-blue-100 rounded-xl text-blue-600"><PieChart size={32} /></div>
                <h3 className="text-3xl font-bold text-slate-800">{data.profitabilityAnalysis.title}</h3>
            </div>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
                <div className="space-y-8">
                     <div className="p-6 bg-slate-50 rounded-2xl border border-slate-100 shadow-inner">
                        <h4 className="text-sm font-bold text-slate-500 uppercase mb-6">{t.revProfitTrend}</h4>
                        <RevenueProfitChart data={data.historicalData} />
                    </div>
                     <div className="p-6 bg-slate-50 rounded-2xl border border-slate-100 shadow-inner">
                        <h4 className="text-sm font-bold text-slate-500 uppercase mb-6">{t.ebitdaMargin}</h4>
                        <MarginTrendChart data={data.historicalData} />
                    </div>
                </div>
                <div className="flex flex-col justify-center">
                    <div className="prose prose-lg prose-slate text-justify">
                        <p className="whitespace-pre-wrap leading-relaxed">{data.profitabilityAnalysis.content}</p>
                    </div>
                </div>
            </div>
        </div>

        {/* === SECTION 6: LIQUIDITY & GROWTH DEEP DIVE === */}
        <div className="report-section bg-white shadow-xl rounded-none sm:rounded-2xl overflow-hidden border border-slate-200 p-12">
            <div className="flex items-center gap-4 mb-8">
                <div className="p-3 bg-purple-100 rounded-xl text-purple-600"><BarChart3 size={32} /></div>
                <h3 className="text-3xl font-bold text-slate-800">{data.liquidityAnalysis.title}</h3>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
                 <div className="flex flex-col justify-center order-2 lg:order-1">
                    <div className="prose prose-lg prose-slate text-justify">
                        <h4 className="font-bold text-slate-800 mb-4">{t.liquidityAnalysis}</h4>
                        <p className="whitespace-pre-wrap leading-relaxed mb-8">{data.liquidityAnalysis.content}</p>
                        
                        <h4 className="font-bold text-slate-800 mb-4">{data.growthAnalysis.title}</h4>
                        <p className="whitespace-pre-wrap leading-relaxed">{data.growthAnalysis.content}</p>
                    </div>
                </div>
                <div className="order-1 lg:order-2 space-y-8">
                    <div className="p-6 bg-slate-50 rounded-2xl border border-slate-100 shadow-inner">
                        <h4 className="text-sm font-bold text-slate-500 uppercase mb-6">{t.costStructure}</h4>
                        <CostStructureChart data={data.historicalData} />
                    </div>
                </div>
            </div>
        </div>

        {/* === SECTION 7: STRATEGIC CONCLUSION === */}
        <div className="report-section bg-slate-900 text-white shadow-xl rounded-none sm:rounded-2xl overflow-hidden border border-slate-800 p-12 flex flex-col justify-center min-h-[600px]">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-16">
                <div>
                    <h3 className="text-3xl font-bold mb-8 flex items-center gap-3 text-yellow-400">
                        <Lightbulb size={32} /> {t.strategic}
                    </h3>
                    <ul className="space-y-6">
                        {data.strategicInsights.map((insight, idx) => (
                            <li key={idx} className="flex gap-5">
                                <span className="flex-shrink-0 w-10 h-10 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center text-lg font-bold text-yellow-500 shadow-lg">
                                    {idx + 1}
                                </span>
                                <p className="text-slate-300 text-lg leading-relaxed">{insight}</p>
                            </li>
                        ))}
                    </ul>
                </div>
                <div>
                    <h3 className="text-3xl font-bold mb-8 flex items-center gap-3 text-emerald-400">
                        <Target size={32} /> {t.recommendations}
                    </h3>
                    <div className="space-y-6">
                        {data.recommendations.map((rec, idx) => (
                            <div key={idx} className="bg-white/5 border border-white/10 rounded-2xl p-6 hover:bg-white/10 transition-colors">
                                <p className="text-slate-200 text-lg leading-relaxed">{rec}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
            
            <div className="mt-20 pt-8 border-t border-slate-800 text-center">
                <p className="text-slate-500 text-sm">
                    {t.generatedBy} • {new Date().getFullYear()} • {t.confidential}
                </p>
            </div>
        </div>
      </div>
    </div>
  );
};
